// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExcludePattern(arg1) {
  return window['go']['main']['App']['AddExcludePattern'](arg1);
}

export function BrowseFolder(arg1) {
  return window['go']['main']['App']['BrowseFolder'](arg1);
}

export function BulkSync(arg1) {
  return window['go']['main']['App']['BulkSync'](arg1);
}

export function CancelOperation(arg1) {
  return window['go']['main']['App']['CancelOperation'](arg1);
}

export function DetectExistingSetup(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DetectExistingSetup'](arg1, arg2, arg3, arg4);
}

export function ExcludeFile(arg1) {
  return window['go']['main']['App']['ExcludeFile'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetBinaryPage() {
  return window['go']['main']['App']['GetBinaryPage']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConflictDetail(arg1) {
  return window['go']['main']['App']['GetConflictDetail'](arg1);
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetFileDiff(arg1) {
  return window['go']['main']['App']['GetFileDiff'](arg1);
}

export function GetFileTree() {
  return window['go']['main']['App']['GetFileTree']();
}

export function GetProjectList() {
  return window['go']['main']['App']['GetProjectList']();
}

export function GetSnapshotDetail(arg1) {
  return window['go']['main']['App']['GetSnapshotDetail'](arg1);
}

export function GetSnapshotList(arg1) {
  return window['go']['main']['App']['GetSnapshotList'](arg1);
}

export function InitJoinExisting(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['InitJoinExisting'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function InitNewDevice(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['InitNewDevice'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function IsInitialized() {
  return window['go']['main']['App']['IsInitialized']();
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function QuickPull() {
  return window['go']['main']['App']['QuickPull']();
}

export function QuickPush() {
  return window['go']['main']['App']['QuickPush']();
}

export function QuickSync() {
  return window['go']['main']['App']['QuickSync']();
}

export function RemoveExcludePattern(arg1) {
  return window['go']['main']['App']['RemoveExcludePattern'](arg1);
}

export function ResolveConflict(arg1, arg2) {
  return window['go']['main']['App']['ResolveConflict'](arg1, arg2);
}

export function SaveMergedConflict(arg1, arg2) {
  return window['go']['main']['App']['SaveMergedConflict'](arg1, arg2);
}

export function SetConfigField(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetConfigField'](arg1, arg2, arg3);
}

export function SetWebDAVPassword(arg1) {
  return window['go']['main']['App']['SetWebDAVPassword'](arg1);
}

export function StartAsync(arg1, arg2) {
  return window['go']['main']['App']['StartAsync'](arg1, arg2);
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function TestWebDAVConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestWebDAVConnection'](arg1, arg2, arg3, arg4);
}
