// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseFolder(arg1) {
  return window['go']['main']['App']['BrowseFolder'](arg1);
}

export function CancelOperation(arg1) {
  return window['go']['main']['App']['CancelOperation'](arg1);
}

export function DetectExistingSetup(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DetectExistingSetup'](arg1, arg2, arg3, arg4);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function InitJoinExisting(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['InitJoinExisting'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function InitNewDevice(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['InitNewDevice'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function IsInitialized() {
  return window['go']['main']['App']['IsInitialized']();
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function QuickPull() {
  return window['go']['main']['App']['QuickPull']();
}

export function QuickPush() {
  return window['go']['main']['App']['QuickPush']();
}

export function QuickSync() {
  return window['go']['main']['App']['QuickSync']();
}

export function StartAsync(arg1, arg2) {
  return window['go']['main']['App']['StartAsync'](arg1, arg2);
}

export function TestWebDAVConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestWebDAVConnection'](arg1, arg2, arg3, arg4);
}
