// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddExcludePattern(arg1:string):Promise<void>;

export function AddProjectPath(arg1:string):Promise<void>;

export function BrowseFolder(arg1:string):Promise<string>;

export function BulkSync(arg1:string):Promise<number>;

export function CancelOperation(arg1:number):Promise<void>;

export function ChangeEncryptionPassword(arg1:string,arg2:string):Promise<void>;

export function DeleteCloudBinaryVersion(arg1:string):Promise<void>;

export function DeleteLocalVersion(arg1:string):Promise<void>;

export function DeleteOrphan(arg1:string):Promise<void>;

export function DetectExistingSetup(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function ExcludeFile(arg1:string):Promise<void>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetBinaryPage():Promise<main.BinaryPageData>;

export function GetBinaryStorage():Promise<main.BinaryStorageInfo>;

export function GetConfig():Promise<main.ConfigView>;

export function GetConflictDetail(arg1:string):Promise<main.ConflictDetail>;

export function GetDashboard():Promise<main.DashboardData>;

export function GetEncryptionStatus():Promise<main.EncryptionStatus>;

export function GetFileContent(arg1:string):Promise<main.FileDetail>;

export function GetFileDiff(arg1:string):Promise<main.DiffResult>;

export function GetFileTree():Promise<main.FileTreeResult>;

export function GetLocalSnapshotList(arg1:number):Promise<Array<main.SnapshotEntry>>;

export function GetProjectDetail(arg1:string):Promise<string>;

export function GetProjectList():Promise<main.ProjectListResult>;

export function GetSnapshotDetail(arg1:string):Promise<main.SnapshotDetail>;

export function GetSnapshotList(arg1:number):Promise<Array<main.SnapshotEntry>>;

export function InitJoinExisting(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function InitNewDevice(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function IsInitialized():Promise<boolean>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function QuickPull():Promise<number>;

export function QuickPush():Promise<number>;

export function QuickSync():Promise<number>;

export function RemoveExcludePattern(arg1:string):Promise<void>;

export function ResolveConflict(arg1:string,arg2:string):Promise<void>;

export function RevertToSnapshot(arg1:string):Promise<void>;

export function SaveMergedConflict(arg1:string,arg2:string):Promise<void>;

export function SetConfigField(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetWebDAVPassword(arg1:string):Promise<void>;

export function StartAsync(arg1:string,arg2:any):Promise<number>;

export function SwitchBinaryVersion(arg1:string,arg2:string):Promise<void>;

export function TestConnection():Promise<main.ConnectionTest>;

export function TestWebDAVConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UploadBinaryVersion(arg1:string):Promise<number>;

export function UploadCurrentBinary():Promise<number>;

export function VerifyEncryptionKey():Promise<boolean>;
