// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseFolder(arg1:string):Promise<string>;

export function CancelOperation(arg1:number):Promise<void>;

export function DetectExistingSetup(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetDashboard():Promise<main.DashboardData>;

export function InitJoinExisting(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function InitNewDevice(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function IsInitialized():Promise<boolean>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function QuickPull():Promise<number>;

export function QuickPush():Promise<number>;

export function QuickSync():Promise<number>;

export function StartAsync(arg1:string,arg2:any):Promise<number>;

export function TestWebDAVConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
